# Generated by Django 5.0.7 on 2024-07-12 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bank', models.CharField(max_length=200, null=True)),
                ('atas_nama', models.CharField(max_length=200, null=True)),
                ('nomor_rekening', models.CharField(max_length=200, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tahun Pelajaran',
            },
        ),
        migrations.CreateModel(
            name='Jenis_pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pembayaran', models.CharField(max_length=200, null=True)),
                ('nominal', models.PositiveIntegerField(null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Jenis Pembayaran',
            },
        ),
        migrations.CreateModel(
            name='Tahun_pelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tahun Pelajaran',
            },
        ),
        migrations.CreateModel(
            name='Wilayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_wilayah', models.CharField(max_length=200, null=True)),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'wilayah',
            },
        ),
        migrations.CreateModel(
            name='Bendahara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bendahara', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=200, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bendahara',
            },
        ),
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_santri', models.CharField(blank=True, max_length=200, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=200, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=100, null=True)),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wilayah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.wilayah')),
            ],
            options={
                'verbose_name_plural': 'santri',
            },
        ),
        migrations.CreateModel(
            name='Detail_nominal_santri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_pembayaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.jenis_pembayaran')),
                ('santri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.santri')),
            ],
            options={
                'verbose_name_plural': 'Detail Nominal santri',
            },
        ),
        migrations.CreateModel(
            name='SettingPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=200, null=True)),
                ('bulan', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Baru', 'Baru'), ('Belum Lunas', 'Belum Lunas'), ('Lunas', 'Lunas')], max_length=200, null=True)),
                ('biaya', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('santri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.santri')),
                ('wilayah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.wilayah')),
            ],
            options={
                'verbose_name_plural': 'Setting Pembayaran',
            },
        ),
    ]
