# Generated by Django 5.0.7 on 2024-07-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingpembayaran',
            name='status',
            field=models.CharField(choices=[('Belum Lunas', 'Belum Lunas'), ('Lunas', 'Lunas')], max_length=200, null=True),
        ),
    ]
